"complete" app
Portal-analytics/swe-pomodoro pull request #4
Opened 2017-06-06 18:06 UTC by 20rohrichtt

2017-06-06 18:12 UTC, mitchgillin reviewed
Remove Console logs

2017-06-06 18:12 UTC, mtg4ra commented on pomodoro/src/Timer.js
> +      console.log(2 * this.state.count);
Remove Console Log

2017-06-06 18:12 UTC, mtg4ra commented on pomodoro/src/Timer.js
> +    console.log(this.state.totalTime);
Remove Console.log

2017-06-06 18:12 UTC, mtg4ra commented on pomodoro/src/Timer.js
> +    console.log(this.state.name);
Remove Console.log

2017-06-06 18:16 UTC, mitchgillin submitted a review, later dismissed

2021-12-22 18:28 UTC, mdcrawford commented
@mitchgillin can we please keep the console.logs they were all the rage in 2017

2021-12-22 19:58 UTC, mitchgillin commented
> @mitchgillin can we please keep the console.logs they were all the rage in 2017

Approved

2021-12-22 19:58 UTC, mitchgillin approved these changes

2022-02-07 18:46 UTC, brentbaum requested changes, later dismissed
Not "complete"

Our work is never done

2024-05-03 17:09 UTC, mdcrawford requested changes, later dismissed
`console.log` had a brief resurgence in 2021 but are considered distasteful again.  I don't make the rules.

2026-01-05 21:25 UTC, mitchgillin commented
Inadequate proof of completion to close PR

2026-01-08 21:23 UTC, merged